name: Full tests on Mac and Windows
on: pull_request
jobs:
  run:
    name: Full tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install this package and pytest, on development mode
        env:
            NWB_CONVERSION_INSTALL_MODE: development
        run: |
          pip install -r requirements-full.txt
          pip install -e .
          pip install pytest
      - name: Get ephy_testing_data current head hash
        id: ephy
        run: echo "::set-output name=HASH_EPHYS_DATASET::$(git ls-remote https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git HEAD | cut -f1)"
      - name: Get ephy_testing_data current head hash
        id: ophys
        run: echo "::set-output name=HASH_OPHYS_DATASET::$(git ls-remote https://gin.g-node.org/CatalystNeuro/ophys_testing_data.git HEAD | cut -f1)"
      - name: Cache ephys dataset - ${{ steps.ophys.outputs.HASH_EPHYS_DATASET }}
        uses: actions/cache@v2
        id: cache-ephy-dataset
        with:
          path: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/ephy_testing_data
          key: ephys-dset-${{ steps.vars.outputs.HASH_EPHYS_DATASET }}
          restore-keys: ephys-dset-${{ steps.vars.outputs.HASH_EPHYS_DATASET }}
      - name: Cache ophys dataset - ${{ steps.ophys.outputs.HASH_OPHYS_DATASET }}
        uses: actions/cache@v2
        id: cache-ophys-dataset
        with:
          path: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/ophys_testing_data
          key: ophys-dset-${{ steps.vars.outputs.HASH_OPHYS_DATASET }}
          restore-keys: ophys-dset-${{ steps.vars.outputs.HASH_OPHYS_DATASET }}
      - name: Run pytest
        run: pytest
