name: Full tests on Linux
on: pull_request
jobs:
  run:
    name: Full tests on Linux
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install this package and pytest, on development mode
      env:
          NWB_CONVERSION_INSTALL_MODE: development
      run: |
        pip install -e .
        pip install pytest
        pip install pytest-cov
    - name: Get ephy_testing_data current head hash
      id: vars
      run: echo "::set-output name=HASH_EPHY_DATASET::$(git ls-remote https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git HEAD | cut -f1)"
    - uses: actions/cache@v2
      id: cache-datasets
      with:
        path: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/ephy_testing_data
        key: ecephys-dset-${{ steps.vars.outputs.HASH_EPHY_DATASET }}
        restore-keys: ecephys-dset-${{ steps.vars.outputs.HASH_EPHY_DATASET }}
    - name: Run pytest with coverage
      run: pytest --cov=./ --cov-report xml:/home/runner/work/nwb-conversion-tools/nwb-conversion-tools/coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/coverage.xml
        flags: unittests
        name: codecov-umbrella 
        yml: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/codecov.yml
