name: Partial (lazy) tests on all OS
on: pull_request
jobs:
  run:
    name: Lazy tests on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install this package, on production mode
      env:
          NWB_CONVERSION_INSTALL_MODE: production
      run: |
        pip install -r requirements-minimal.txt
        pip install .
        pip install pytest
    - name: Run tests
      run: pytest tests/test_internals
