name: Minimal and full tests on Linux
on: pull_request
jobs:
  run:
    name: Minimal and full tests on Linux with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: s-weigand/setup-conda@v1
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest
        run: pip install --upgrade pip

      - name: Install nwb-conversion-tools with minimal requirements
        run: pip install .[test]
      - name: Run minimal pytest with coverage
        run: pytest tests/test_internals

      - name: Install full requirements
        run: pip install -e .[full]
      - name: Get ephy_testing_data current head hash
        id: ecephys
        run: echo "::set-output name=HASH_EPHY_DATASET::$(git ls-remote https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git HEAD | cut -f1)"

      - name: Get behavior_testing_data current head hash
        id: behavior
        run: echo "::set-output name=HASH_BEHAVIOR_DATASET::$(git ls-remote https://gin.g-node.org/CatalystNeuro/behavior_testing_data.git HEAD | cut -f1)"
      - name: Cache behavior dataset - ${{ steps.behavior.outputs.HASH_BEHAVIOR_DATASET }}
        uses: actions/cache@v2
        id: cache-behavior-datasets
        with:
          path: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/behavior_testing_data
          key: behavior-datasets-8-${{ steps.behavior.outputs.HASH_behavior_DATASET }}
          restore-keys: behavior-datasets-8-${{ steps.behavior.outputs.HASH_behavior_DATASET }}
      - name: Force GIN behavior download
        if: steps.cache-behavior-datasets.outputs.cache-hit == false
        run: |
          conda install -c conda-forge datalad==0.14.5
          git config --global user.email "CI@example.com"
          git config --global user.name "CI Almighty"
          datalad install -rg https://gin.g-node.org/CatalystNeuro/behavior_testing_data

      - name: Run full pytest with coverage
        run: pytest
