name: Minimal and full tests on Windows
on: pull_request
jobs:
  run:
    name: Minimal and full tests on Windows with Python ${{ matrix.python-version }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest
        run: pip install --user --upgrade pip

      - name: Install nwb-conversion-tools with minimal requirements
        run: pip install .[test]
      - name: Run minimal pytest with coverage
        run: pytest tests/test_internals --cov=./ --cov-report xml:./nwb-conversion-tools/nwb-conversion-tools/minimal-coverage.xml

      - name: Install full requirements
        run: pip install .[full]

      - name: Get ephy_testing_data current head hash
        id: ecephys
        run: echo "::set-output name=HASH_EPHY_DATASET::$(git ls-remote https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git HEAD | cut -f1)"
      - name: Cache ephys dataset - ${{ steps.ecephys.outputs.HASH_EPHYS_DATASET }}
        uses: actions/cache@v2
        id: cache-ecephys-datasets
        with:
          path: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/ephy_testing_data
          key: ecephys-datasets-9-${{ steps.ecephys.outputs.HASH_EPHY_DATASET }}
          restore-keys: ecephys-datasets-9-${{ steps.ecephys.outputs.HASH_EPHY_DATASET }}
      - name: Force GIN ecephys download
        if: steps.cache-ecephys-datasets.outputs.cache-hit == false
        run: |
          conda install -c conda-forge datalad==0.14.5
          git config --global user.email "CI@example.com"
          git config --global user.name "CI Almighty"
          datalad install https://gin.g-node.org/NeuralEnsemble/ephy_testing_data
          cd ephy_testing_data
          datalad get -r ./neuralynx/Cheetah_v5.7.4/original_data/
          datalad get -r ./neuroscope/test1/
          datalad get -r ./openephysbinary/v0.4.4.1_with_video_tracking/
          datalad get -r ./blackrock/
          datalad get -r ./intan/
          datalad get -r ./spikegadgets/
          datalad get -r ./spikeglx/Noise4Sam_g0/Noise4Sam_g0_imec0/
          datalad get -r ./phy/phy_example_0/
          datalad get -r ./axona/
          datalad get -r ./cellexplorer/
          cd ..

      - name: Get ophys_testing_data current head hash
        id: ophys
        run: echo "::set-output name=HASH_OPHYS_DATASET::$(git ls-remote https://gin.g-node.org/CatalystNeuro/ophys_testing_data.git HEAD | cut -f1)"
      - name: Cache ophys dataset - ${{ steps.ophys.outputs.HASH_OPHYS_DATASET }}
        uses: actions/cache@v2
        id: cache-ophys-datasets
        with:
          path: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/ophys_testing_data
          key: ophys-datasets-8-${{ steps.ophys.outputs.HASH_OPHYS_DATASET }}
          restore-keys: ophys-datasets-8-${{ steps.ophys.outputs.HASH_OPHYS_DATASET }}
      - name: Force GIN ophys download
        if: steps.cache-ophys-datasets.outputs.cache-hit == false
        run: |
          conda install -c conda-forge datalad==0.14.5
          git config --global user.email "CI@example.com"
          git config --global user.name "CI Almighty"
          datalad install -rg https://gin.g-node.org/CatalystNeuro/ophys_testing_data

      - name: Get behavior_testing_data current head hash
        id: behavior
        run: echo "::set-output name=HASH_BEHAVIOR_DATASET::$(git ls-remote https://gin.g-node.org/CatalystNeuro/behavior_testing_data.git HEAD | cut -f1)"
      - name: Cache behavior dataset - ${{ steps.behavior.outputs.HASH_BEHAVIOR_DATASET }}
        uses: actions/cache@v2
        id: cache-behavior-datasets
        with:
          path: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/behavior_testing_data
          key: behavior-datasets-8-${{ steps.behavior.outputs.HASH_behavior_DATASET }}
          restore-keys: behavior-datasets-8-${{ steps.behavior.outputs.HASH_behavior_DATASET }}
      - name: Force GIN behavior download
        if: steps.cache-behavior-datasets.outputs.cache-hit == false
        run: |
          echo "${{ steps.cache-behavior-datasets.outputs.cache-hit }}"
          conda install -c conda-forge datalad==0.14.5
          git config --global user.email "CI@example.com"
          git config --global user.name "CI Almighty"
          datalad install -rg https://gin.g-node.org/CatalystNeuro/behavior_testing_data

      - name: Run pytest with GIN data
        run: |
          echo "behavior cache {{ steps.cache-behavior-datasets.outputs.cache-hit }}"
          echo "ecephys cache {{ steps.cache-ecephys-datasets.outputs.cache-hit }}"
          echo "ophys cache {{ steps.cache-ophys-datasets.outputs.cache-hit }}"
          pytest
