name: Minimal and full tests on Mac
on: pull_request
jobs:
  run:
    name: Minimal and full tests on Mac with Python ${{ matrix.python-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest
        run: pip install --upgrade pip

      - name: Install nwb-conversion-tools with minimal requirements
        run: pip install .[test]
      - name: Run minimal pytest with coverage
        run: pytest tests/test_internals --cov=./ --cov-report xml:./nwb-conversion-tools/nwb-conversion-tools/minimal-coverage.xml
      - if: ${{ matrix.python-version == '3.7' || matrix.python-version == '3.9' }}
        name: Upload minimal coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./nwb-conversion-tools/nwb-conversion-tools/minimal-coverage.xml
          flags: unittests
          name: codecov-umbrella 
          yml: ./nwb-conversion-tools/nwb-conversion-tools/codecov.yml

      - name: Install full requirements
        run: pip install .[full]
      - name: Install git-annex
        run: brew install git-annex
      - name: Install datalad
        run: |
          pip install datalad
          git config --global user.email "CI@example.com"
          git config --global user.name "CI Almighty"

      - name: Get behavior_testing_data current head hash
        id: behavior
        run: echo "::set-output name=HASH_BEHAVIOR_DATASET::$(git ls-remote https://gin.g-node.org/CatalystNeuro/behavior_testing_data.git HEAD | cut -f1)"
      - name: Cache behavior dataset - ${{ steps.behavior.outputs.HASH_BEHAVIOR_DATASET }}
        uses: actions/cache@v2
        id: cache-behavior-datasets
        with:
          path: ./behavior_testing_data
          key: behavior-datasets-00-${{ steps.behavior.outputs.HASH_behavior_DATASET }}
      - name: Force GIN behavior download
        if: steps.cache-behavior-datasets.outputs.cache-hit == false
        run: datalad install -rg https://gin.g-node.org/CatalystNeuro/behavior_testing_data
      - name: Run pytest on GIN data
        run: pytest tests/test_on_data/test_gin_behavior.py
